---
- name: Create Docker Configuration Directory
  become: yes
  file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: 0755
  when: docker_engine_install

- name: Place Docker Configuration File
  become: yes
  template:
      src: templates/root-dir.conf.j2
      dest: /etc/systemd/system/docker.service.d/root-dir.conf
      owner: root
      group: root
      mode: 444
      backup: no
  when: docker_engine_install

- name: Download Docker Engine Installation Script
  become: no
  get_url:
      url: "https://get.docker.com/"
      dest: "{{ansible_user_dir}}/{{docker_download_directory}}/docker-install.sh"
      mode: 0554
  when: docker_engine_install

- name: Run Docker Engine Installer
  become: yes
  shell: "{{ansible_user_dir}}/{{docker_download_directory}}/docker-install.sh"
  when: docker_engine_install

- name: Save Non-Root User
  become: no
  set_fact:
      standard_user: "{{ansible_user_id}}"
  when: docker_engine_install

- name: Add Non-Root User To Docker Group
  become: yes
  user:
      name: "{{standard_user}}"
      groups: docker
      append: yes
  when: docker_engine_install

# TODO: when Ansible 2.2 comes out, switch to using this module instead
#   - systemd: state=restarted daemon_reload=yes name=docker
- name: Restart Docker
  become: yes
  command: /bin/systemctl restart docker
  when: docker_engine_install

- name: Test Docker
  become: yes
  command: /usr/bin/docker run --rm hello-world
  when: docker_engine_install

- name: Download Docker Compose Binary
  become: yes
  get_url:
      url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-x86_64"
      dest: "/usr/local/bin/docker-compose"
      mode: 0555
  when: docker_compose_install

- name: Test Docker Compose
  become: no
  shell: "/usr/local/bin/docker-compose --version"
  when: docker_compose_install

- name: Download Docker Machine Binary
  become: yes
  get_url:
      url: "https://github.com/docker/machine/releases/download/v{{docker_machine_version}}/docker-machine-Linux-x86_64"
      dest: "/usr/local/bin/docker-machine"
      mode: 0555
  when: docker_machine_install

- name: Test Docker Machine
  become: no
  shell: "/usr/local/bin/docker-machine --version"
  when: docker_machine_install


